-- ═══════════════════════════════════════════════════════════════════
-- SCHEMA EXPANDIDO — TPV-SORVETERIA-FINAL
-- Melhorias: tabela products, campo origem em orders, toppings jsonb
-- ═══════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ─── Tabela existente: categories ─────────────────────────────────
create table if not exists public.categories (
  id text primary key,
  nome jsonb not null,
  base_price numeric(10,2) not null,
  max_flavors integer not null,
  cor_hex text not null,
  active boolean not null default true,
  display_order integer not null,
  image_url text not null,
  badge text
);

-- ─── Tabela existente: flavors ────────────────────────────────────
create table if not exists public.flavors (
  id text primary key,
  nome jsonb not null,
  categoria text not null,
  cor_hex text not null,
  image_url text not null,
  extra_price numeric(10,2) not null default 0,
  stock_buckets numeric(10,3) not null default 0,
  low_stock_threshold numeric(10,3) not null default 1,
  available boolean not null default true,
  badge text
);

-- ─── Tabela existente: toppings (ATUALIZADA para jsonb nome) ──────
create table if not exists public.toppings (
  id text primary key,
  nome jsonb not null,
  price numeric(10,2) not null,
  categoria text not null,
  emoji text
);

-- ─── NOVA TABELA: products (catálogo expandido do Local) ──────────
create table if not exists public.products (
  id text primary key,
  nome jsonb not null,
  preco numeric(10,2) not null,
  image_url text not null,
  categoria_slug text not null,
  descricao jsonb,
  em_estoque boolean not null default true,
  badge jsonb,
  created_at timestamptz not null default now()
);

-- Índices para products
create index if not exists idx_products_categoria on public.products(categoria_slug);
create index if not exists idx_products_estoque on public.products(em_estoque);

-- ─── Tabela existente: store_settings ─────────────────────────────
create table if not exists public.store_settings (
  store_key text primary key default 'main',
  name text not null,
  nif text not null,
  address text not null,
  summer_hours text not null,
  winter_hours text not null,
  updated_at timestamptz not null default now()
);

-- ─── Tabela existente: orders (EXPANDIDA com origem + nome_usuario) ─
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  numero_sequencial bigint generated by default as identity unique,
  status text not null,
  created_at timestamptz not null default now(),
  ready_at timestamptz,
  payment_method text not null,
  subtotal numeric(10,2) not null default 0,
  discount numeric(10,2) not null default 0,
  extras numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  iva numeric(10,2) not null,
  verifactu_qr text,
  customer_phone text,
  origem text not null default 'tpv' check (origem in ('tpv', 'pwa')),
  nome_usuario text
);

-- Índice para filtrar por origem
create index if not exists idx_orders_origem on public.orders(origem);
create index if not exists idx_orders_status on public.orders(status);

-- ─── Tabela existente: order_items ────────────────────────────────
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  sort_order integer not null default 0,
  category_sku text not null,
  category_name text not null,
  flavors jsonb not null default '[]'::jsonb,
  toppings jsonb not null default '[]'::jsonb,
  unit_price numeric(10,2) not null,
  quantity integer not null default 1,
  notes text
);

-- ═══════════════════════════════════════════════════════════════════
-- RLS (Row Level Security)
-- ═══════════════════════════════════════════════════════════════════

alter table public.categories enable row level security;
alter table public.flavors enable row level security;
alter table public.toppings enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists categories_read_demo on public.categories;
create policy categories_read_demo on public.categories for select to anon, authenticated using (true);

drop policy if exists flavors_read_demo on public.flavors;
create policy flavors_read_demo on public.flavors for select to anon, authenticated using (true);

drop policy if exists toppings_read_demo on public.toppings;
create policy toppings_read_demo on public.toppings for select to anon, authenticated using (true);

drop policy if exists products_read_demo on public.products;
create policy products_read_demo on public.products for select to anon, authenticated using (true);

drop policy if exists settings_read_demo on public.store_settings;
create policy settings_read_demo on public.store_settings for select to anon, authenticated using (true);

drop policy if exists orders_read_demo on public.orders;
create policy orders_read_demo on public.orders for select to anon, authenticated using (true);

drop policy if exists order_items_read_demo on public.order_items;
create policy order_items_read_demo on public.order_items for select to anon, authenticated using (true);

-- ═══════════════════════════════════════════════════════════════════
-- FUNCTIONS (RPCs)
-- ═══════════════════════════════════════════════════════════════════

create or replace function public.serialize_flavors(flavor_ids text[])
returns jsonb
language sql
stable
set search_path = public
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', f.id,
        'nome', f.nome,
        'categoria', f.categoria,
        'corHex', f.cor_hex,
        'imagemUrl', f.image_url,
        'precoExtra', f.extra_price,
        'stockBaldes', f.stock_buckets,
        'alertaStock', f.low_stock_threshold,
        'disponivel', f.available,
        'badge', f.badge
      )
      order by array_position(flavor_ids, f.id)
    ),
    '[]'::jsonb
  )
  from public.flavors f
  where f.id = any(flavor_ids);
$$;

create or replace function public.serialize_toppings(topping_ids text[])
returns jsonb
language sql
stable
set search_path = public
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', t.id,
        'nome', t.nome,
        'preco', t.price,
        'categoria', t.categoria,
        'emoji', t.emoji
      )
      order by array_position(topping_ids, t.id)
    ),
    '[]'::jsonb
  )
  from public.toppings t
  where t.id = any(topping_ids);
$$;

create or replace function public.calculate_item_unit_price(category_id_input text, flavor_ids text[], topping_ids text[])
returns numeric
language sql
stable
set search_path = public
as $$
  select
    c.base_price
    + coalesce((select sum(f.extra_price) from public.flavors f where f.id = any(flavor_ids)), 0)
    + coalesce((select sum(t.price) from public.toppings t where t.id = any(topping_ids)), 0)
  from public.categories c
  where c.id = category_id_input;
$$;

-- ─── NOVA RPC: get_products_by_category ───────────────────────────
create or replace function public.get_products_by_category(categoria_input text)
returns setof public.products
language sql
stable
set search_path = public
as $$
  select * from public.products
  where categoria_slug = categoria_input and em_estoque = true
  order by created_at desc;
$$;

-- ─── NOVA RPC: update_product_stock ───────────────────────────────
create or replace function public.update_product_stock(product_id_input text, em_estoque_input boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.products
  set em_estoque = em_estoque_input
  where id = product_id_input;
end;
$$;

-- ─── RPC existente: create_demo_order (ATUALIZADA com origem) ────
create or replace function public.create_demo_order(
  cart_payload jsonb,
  payment_method_input text,
  checkout_payload jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  item_record jsonb;
  category_id text;
  category_name text;
  flavor_ids text[];
  topping_ids text[];
  flavor_count integer;
  total_consumption numeric(10,3);
  consumption_per_flavor numeric(10,3);
  item_price numeric(10,2);
  items_subtotal numeric(10,2) := 0;
  extras_total numeric(10,2) := case when coalesce((checkout_payload->>'coffeeAdded')::boolean, false) then coalesce((checkout_payload->>'coffeePrice')::numeric, 1.50) else 0 end;
  discount_rate numeric(10,4) := greatest(coalesce((checkout_payload->>'promoDiscountRate')::numeric, 0), 0);
  discount_total numeric(10,2);
  subtotal_total numeric(10,2);
  iva_total numeric(10,2);
  grand_total numeric(10,2);
  order_id_output uuid;
  order_number_output bigint;
  item_index integer := 0;
  order_origem text := coalesce(checkout_payload->>'origem', 'tpv');
  order_nome_usuario text := nullif(checkout_payload->>'nomeUsuario', '');
begin
  if cart_payload is null or jsonb_typeof(cart_payload) <> 'array' or jsonb_array_length(cart_payload) = 0 then
    raise exception 'cart_payload must contain at least one item';
  end if;

  for item_record in select value from jsonb_array_elements(cart_payload)
  loop
    category_id := item_record->'categoria'->>'id';
    select nome->>'es' into category_name from public.categories where id = category_id and active = true;
    if category_name is null then
      raise exception 'Category % not found or inactive', category_id;
    end if;

    select coalesce(array_agg(value->>'id'), array[]::text[])
      into flavor_ids
      from jsonb_array_elements(coalesce(item_record->'sabores', '[]'::jsonb));

    select coalesce(array_agg(value->>'id'), array[]::text[])
      into topping_ids
      from jsonb_array_elements(coalesce(item_record->'toppings', '[]'::jsonb));

    if coalesce(array_length(flavor_ids, 1), 0) = 0 then
      raise exception 'Each cart item must contain at least one flavor';
    end if;

    select count(*) into flavor_count from public.flavors where id = any(flavor_ids) and available = true;
    if flavor_count <> array_length(flavor_ids, 1) then
      raise exception 'One or more selected flavors are unavailable';
    end if;

    item_price := round(public.calculate_item_unit_price(category_id, flavor_ids, topping_ids), 2);
    items_subtotal := items_subtotal + item_price;
  end loop;

  discount_total := round(items_subtotal * discount_rate, 2);
  subtotal_total := round(items_subtotal + extras_total - discount_total, 2);
  iva_total := round(subtotal_total * 0.10, 2);
  grand_total := round(subtotal_total + iva_total, 2);

  insert into public.orders (
    status,
    payment_method,
    subtotal,
    discount,
    extras,
    total,
    iva,
    customer_phone,
    origem,
    nome_usuario
  )
  values (
    'pendiente',
    payment_method_input,
    subtotal_total,
    discount_total,
    extras_total,
    grand_total,
    iva_total,
    nullif(checkout_payload->>'notificationPhone', ''),
    order_origem,
    order_nome_usuario
  )
  returning id, numero_sequencial into order_id_output, order_number_output;

  update public.orders
  set verifactu_qr = jsonb_build_object(
    'id', concat('pedido-', order_number_output),
    'fecha', current_date,
    'importe', to_char(grand_total, 'FM999999990.00'),
    'establecimiento', (select name from public.store_settings where store_key = 'main')
  )::text
  where id = order_id_output;

  for item_record in select value from jsonb_array_elements(cart_payload)
  loop
    item_index := item_index + 1;
    category_id := item_record->'categoria'->>'id';
    select nome->>'es' into category_name from public.categories where id = category_id;

    select coalesce(array_agg(value->>'id'), array[]::text[])
      into flavor_ids
      from jsonb_array_elements(coalesce(item_record->'sabores', '[]'::jsonb));

    select coalesce(array_agg(value->>'id'), array[]::text[])
      into topping_ids
      from jsonb_array_elements(coalesce(item_record->'toppings', '[]'::jsonb));

    item_price := round(public.calculate_item_unit_price(category_id, flavor_ids, topping_ids), 2);

    insert into public.order_items (
      order_id,
      sort_order,
      category_sku,
      category_name,
      flavors,
      toppings,
      unit_price,
      quantity,
      notes
    )
    values (
      order_id_output,
      item_index,
      category_id,
      category_name,
      public.serialize_flavors(flavor_ids),
      public.serialize_toppings(topping_ids),
      item_price,
      1,
      nullif(item_record->>'notas', '')
    );

    total_consumption := case
      when category_id = 'copo500' then 0.100
      when category_id = 'copo300' then 0.052
      when category_id = 'cone' then 0.031
      else 0.200
    end;

    consumption_per_flavor := round(total_consumption / greatest(array_length(flavor_ids, 1), 1), 3);

    update public.flavors
    set stock_buckets = greatest(0, round(stock_buckets - consumption_per_flavor, 3))
    where id = any(flavor_ids);
  end loop;

  return order_id_output;
end;
$$;

-- ─── RPC existente: update_order_status ───────────────────────────
create or replace function public.update_order_status(order_id_input uuid, status_input text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders
  set
    status = status_input,
    ready_at = case when status_input = 'listo' then now() else ready_at end
  where id = order_id_input;
end;
$$;

-- ─── RPC existente: adjust_flavor_stock ───────────────────────────
create or replace function public.adjust_flavor_stock(flavor_id_input text, delta_input numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.flavors
  set stock_buckets = greatest(0, round(stock_buckets + delta_input, 3))
  where id = flavor_id_input;
end;
$$;

-- ─── RPC existente: set_flavor_availability ──────────────────────
create or replace function public.set_flavor_availability(flavor_id_input text, available_input boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.flavors
  set available = available_input
  where id = flavor_id_input;
end;
$$;

-- ─── RPC existente: upsert_store_settings ────────────────────────
create or replace function public.upsert_store_settings(setting_payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.store_settings (
    store_key,
    name,
    nif,
    address,
    summer_hours,
    winter_hours
  )
  values (
    'main',
    coalesce(setting_payload->>'name', 'Heladeria Sabadell Nord'),
    coalesce(setting_payload->>'nif', 'B-12345678'),
    coalesce(setting_payload->>'address', 'Carrer de la Concepcio, 23, 08201 Sabadell, Barcelona'),
    coalesce(setting_payload->>'summerHours', '16:00 - 23:00'),
    coalesce(setting_payload->>'winterHours', '17:00 - 22:00')
  )
  on conflict (store_key) do update
  set
    name = excluded.name,
    nif = excluded.nif,
    address = excluded.address,
    summer_hours = excluded.summer_hours,
    winter_hours = excluded.winter_hours,
    updated_at = now();
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- SEED DATA (Dados iniciais)
-- ═══════════════════════════════════════════════════════════════════

create or replace function public.reset_demo_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  order_one uuid;
  order_two uuid;
  order_three uuid;
  order_four uuid;
  order_five uuid;
  order_six uuid;
begin
  truncate table public.order_items, public.orders restart identity cascade;
  truncate table public.categories, public.flavors, public.toppings, public.products, public.store_settings cascade;

  -- Categorias do Kiosk
  insert into public.categories (id, nome, base_price, max_flavors, cor_hex, active, display_order, image_url, badge) values
    ('copo300', '{"ca":"Got 300ml","es":"Vaso 300ml","en":"Cup 300ml","pt":"Copo 300ml"}', 3.50, 2, '#4ECDC4', true, 0, '/assets/demo/categoria-copo300.jpg', 'Popular'),
    ('copo500', '{"ca":"Got 500ml","es":"Vaso 500ml","en":"Cup 500ml","pt":"Copo 500ml"}', 4.80, 3, '#FF6B9D', true, 1, '/assets/demo/categoria-copo500.jpg', 'Mas valor'),
    ('cone', '{"ca":"Cucurutxo","es":"Cono","en":"Cone","pt":"Cone"}', 3.20, 2, '#D2691E', true, 2, '/assets/demo/categoria-cone.jpg', null),
    ('pote1l', '{"ca":"Tarrina 1L","es":"Tarrina 1L","en":"Tub 1L","pt":"Pote 1L"}', 12.00, 4, '#98D8C8', true, 3, '/assets/demo/categoria-pote1l.jpg', 'Para llevar');

  -- Sabores artesanais
  insert into public.flavors (id, nome, categoria, cor_hex, image_url, extra_price, stock_buckets, low_stock_threshold, available, badge) values
    ('crema_catalana', '{"ca":"Crema Catalana","es":"Crema Catalana","en":"Crema Catalana","pt":"Creme Catalã"}', 'cremoso', '#FFF8E7', '/assets/sabores/sabor-crema-catalana-real.jpg', 0, 2.5, 1.0, true, null),
    ('choco_negro', '{"ca":"Xocolata Negre 70%","es":"Chocolate Negro 70%","en":"Dark Chocolate 70%","pt":"Chocolate Preto 70%"}', 'chocolate', '#3C1414', '/assets/sabores/sabor-choco-negro-real.jpg', 0, 5.0, 1.0, true, null),
    ('vainilla_madagascar', '{"ca":"Vainilla Madagascar","es":"Vainilla Madagascar","en":"Madagascar Vanilla","pt":"Baunilha Madagascar"}', 'cremoso', '#F3E5AB', '/assets/sabores/sabor-vainilla-madagascar-real.jpg', 0, 3.0, 1.0, true, null),
    ('menta_fresca', '{"ca":"Menta Fresca","es":"Menta Fresca","en":"Fresh Mint","pt":"Menta Fresca"}', 'especial', '#98FF98', '/assets/sabores/sabor-menta-fresca-real.jpg', 0, 1.5, 1.0, true, null),
    ('stracciatella', '{"ca":"Stracciatella","es":"Stracciatella","en":"Stracciatella","pt":"Stracciatella"}', 'especial', '#FFFFF0', '/assets/sabores/sabor-stracciatella-real.jpg', 0.50, 4.0, 1.0, true, 'Premium'),
    ('cafe_espresso', '{"ca":"Cafe Espresso","es":"Cafe Espresso","en":"Espresso Coffee","pt":"Café Espresso"}', 'especial', '#6F4E37', '/assets/sabores/sabor-cafe-espresso-real.jpg', 0.30, 2.0, 1.0, true, null),
    ('tiramisu', '{"ca":"Tiramisu","es":"Tiramisu","en":"Tiramisu","pt":"Tiramisu"}', 'especial', '#D2B48C', '/assets/sabores/sabor-tiramisu-real.jpg', 0.50, 1.8, 1.0, true, null),
    ('coco_tropical', '{"ca":"Coco Tropical","es":"Coco Tropical","en":"Tropical Coconut","pt":"Coco Tropical"}', 'fruta', '#FFF5EE', '/assets/sabores/sabor-coco-tropical-real.jpg', 0, 2.2, 1.0, true, null),
    ('pistacho', '{"ca":"Festuc Premium","es":"Pistacho Premium","en":"Premium Pistachio","pt":"Pistacho Premium"}', 'frutos_secos', '#93C572', '/assets/sabores/sabor-pistacho-real.jpg', 0.80, 0.8, 1.0, true, 'Premium'),
    ('frutos_rojos', '{"ca":"Fruits Vermells","es":"Frutos Rojos","en":"Red Berries","pt":"Frutos Vermelhos"}', 'sorbete', '#DC143C', '/assets/sabores/sabor-frutos-rojos-real.jpg', 0, 1.2, 1.0, true, null),
    ('mango_alphonso', '{"ca":"Mango Alphonso","es":"Mango Alphonso","en":"Alphonso Mango","pt":"Mango Alphonso"}', 'sorbete', '#FF8C00', '/assets/sabores/sabor-mango-alphonso-real.jpg', 0, 1.5, 1.0, true, null),
    ('limon_siciliano', '{"ca":"Llimona Siciliana","es":"Limon Siciliano","en":"Sicilian Lemon","pt":"Limão Siciliano"}', 'sorbete', '#FAFAD2', '/assets/sabores/sabor-limon-siciliano-real.jpg', 0, 2.0, 1.0, true, null),
    ('turron_jijona', '{"ca":"Turro de Jijona","es":"Turron de Jijona","en":"Jijona Nougat","pt":"Torrão de Jijona"}', 'especial', '#CD853F', '/assets/sabores/sabor-turron-jijona-real.jpg', 0.60, 1.0, 1.0, true, 'Temporada'),
    ('yogurt_griego', '{"ca":"Iogurt Grec","es":"Yogurt Griego","en":"Greek Yogurt","pt":"Iogurte Grego"}', 'cremoso', '#F5F5DC', '/assets/sabores/sabor-yogurt-griego-real.jpg', 0, 3.5, 1.0, true, null),
    ('amarena', '{"ca":"Amarena","es":"Amarena","en":"Amarena Cherry","pt":"Amarena"}', 'especial', '#8B0000', '/assets/sabores/sabor-amarena-real.jpg', 0.70, 0.5, 1.0, true, 'Ultimas');

  -- Toppings com nomes localizados (jsonb)
  insert into public.toppings (id, nome, price, categoria, emoji) values
    ('choco_negro_derretido', '{"ca":"Xocolata Negra","es":"Chocolate Negro","pt":"Chocolate Preto","en":"Dark Chocolate"}', 0.50, 'cobertura', '🍫'),
    ('choco_blanco_derretido', '{"ca":"Xocolata Blanca","es":"Chocolate Blanco","pt":"Chocolate Branco","en":"White Chocolate"}', 0.50, 'cobertura', '🤍'),
    ('nata_montada', '{"ca":"Nata Muntada","es":"Nata Montada","pt":"Chantilly","en":"Whipped Cream"}', 0.60, 'crema', '🥛'),
    ('almendras_caramelizadas', '{"ca":"Ametlles Caramel·litzades","es":"Almendras Caramelizadas","pt":"Amêndoas Caramelizadas","en":"Caramelized Almonds"}', 0.80, 'crocante', '🌰'),
    ('nueces_praline', '{"ca":"Nous Praline","es":"Nueces Praline","pt":"Nozes Praliné","en":"Praline Nuts"}', 0.80, 'crocante', '🥜'),
    ('virutas_choco', '{"ca":"Virutes de Xocolata","es":"Virutas de Chocolate","pt":"Lascas de Chocolate","en":"Chocolate Shavings"}', 0.40, 'decoracion', '🍪'),
    ('sirope_fresa', '{"ca":"Xarop de Maduixa","es":"Sirope de Fresa","pt":"Xarope de Morango","en":"Strawberry Syrup"}', 0.30, 'cobertura', '🍓'),
    ('sirope_caramelo', '{"ca":"Xarop de Caramel","es":"Sirope de Caramelo Salado","pt":"Xarope de Caramelo Salgado","en":"Salted Caramel Syrup"}', 0.40, 'cobertura', '🍯'),
    ('galleta_oreo', '{"ca":"Galeta Oreo Triturada","es":"Galleta Oreo Triturada","pt":"Biscoito Oreo Triturado","en":"Crushed Oreo Cookie"}', 0.60, 'mix-in', '🖤'),
    ('brownie_pieces', '{"ca":"Trossos de Brownie","es":"Trocitos de Brownie","pt":"Pedacinhos de Brownie","en":"Brownie Pieces"}', 0.70, 'mix-in', '🟫');

  -- Produtos do catálogo expandido (Local)
  insert into public.products (id, nome, preco, image_url, categoria_slug, descricao, em_estoque, badge) values
    ('acai-puro-copinho', '{"ca":"Açaí Pur Copet","es":"Açaí Puro Copinho","pt":"Açaí Puro Copinho","en":"Pure Açaí Cup"}', 7.70, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80', 'acai', null, true, null),
    ('acai-com-crema', '{"ca":"Açaí amb Crema","es":"Açaí con Crema","pt":"Açaí com Creme","en":"Açaí with Cream"}', 8.90, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80', 'acai', null, true, null),
    ('picole-chocolate', '{"ca":"Polol Xocolata","es":"Polochocolate","pt":"Picolé de Chocolate","en":"Chocolate Popsicle"}', 3.50, 'https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=400&q=80', 'picole', null, true, null),
    ('picole-premium-pistacho', '{"ca":"Polol Premium Festuc","es":"Pollo Premium Pistacho","pt":"Picolé Premium Pistache","en":"Premium Pistachio Popsicle"}', 5.50, 'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=400&q=80', 'picole-premium', null, true, '{"ca":"Premium","es":"Premium","pt":"Premium","en":"Premium"}'),
    ('cono-barquillo', '{"ca":"Con Cucurutxo","es":"Cono Barquillo","pt":"Cone Barquilho","en":"Waffle Cone"}', 2.50, 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&q=80', 'conos', null, true, null),
    ('sundae-fresa', '{"ca":"Sundae Maduixa","es":"Sundae Fresa","pt":"Sundae de Morango","en":"Strawberry Sundae"}', 6.50, 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80', 'sundae', null, true, null),
    ('donut-glaseado', '{"ca":"Donut Glacejat","es":"Donut Glaseado","pt":"Donut Glaceado","en":"Glazed Donut"}', 3.00, 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&q=80', 'donuts', null, true, null),
    ('yogurt-especial-mora', '{"ca":"Iogurt Especial Mora","es":"Yogurt Especial Mora","pt":"Iogurte Especial Amora","en":"Special Blackberry Yogurt"}', 5.90, 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80', 'yogurt-especial', null, true, null);

  -- Configurações do estabelecimento
  perform public.upsert_store_settings(
    jsonb_build_object(
      'name', 'Heladeria Sabadell Nord',
      'nif', 'B-12345678',
      'address', 'Carrer de la Concepcio, 23, 08201 Sabadell, Barcelona',
      'summerHours', '16:00 - 23:00',
      'winterHours', '17:00 - 22:00'
    )
  );

  -- Pedidos demo com origem
  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (1, 'entregado', '2026-04-18T10:05:00Z', '2026-04-18T10:09:00Z', 'tarjeta', 4.36, 0, 0, 4.80, 0.44, null, 'tpv', null)
  returning id into order_one;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_one, 1, 'copo500', 'Vaso 500ml', public.serialize_flavors(array['crema_catalana','choco_negro']), public.serialize_toppings(array['nata_montada']), 4.80, 1);

  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (2, 'entregado', '2026-04-18T10:15:00Z', '2026-04-18T10:19:00Z', 'efectivo', 3.18, 0, 0, 3.50, 0.32, null, 'tpv', null)
  returning id into order_two;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_two, 1, 'copo300', 'Vaso 300ml', public.serialize_flavors(array['vainilla_madagascar']), '[]'::jsonb, 3.50, 1);

  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (3, 'pendiente', '2026-04-18T10:35:00Z', null, 'tarjeta', 7.27, 0, 0, 8.00, 0.73, null, 'pwa', 'María García')
  returning id into order_three;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_three, 1, 'cone', 'Cono', public.serialize_flavors(array['menta_fresca','tiramisu']), public.serialize_toppings(array['choco_blanco_derretido','sirope_fresa']), 4.00, 2);

  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (4, 'preparando', '2026-04-18T11:00:00Z', null, 'bizum', 10.91, 0, 0, 12.00, 1.09, '612345678', 'pwa', 'Carlos Ruiz')
  returning id into order_four;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_four, 1, 'pote1l', 'Tarrina 1L', public.serialize_flavors(array['crema_catalana','choco_negro','vainilla_madagascar']), public.serialize_toppings(array['nata_montada','sirope_caramelo']), 12.00, 1);

  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (5, 'entregado', '2026-04-18T11:30:00Z', '2026-04-18T11:35:00Z', 'tarjeta', 8.73, 0, 0, 9.60, 0.87, null, 'tpv', null)
  returning id into order_five;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_five, 1, 'copo500', 'Vaso 500ml', public.serialize_flavors(array['choco_negro','stracciatella']), public.serialize_toppings(array['choco_negro_derretido','almendras_caramelizadas']), 4.80, 2);

  insert into public.orders (numero_sequencial, status, created_at, ready_at, payment_method, subtotal, discount, extras, total, iva, customer_phone, origem, nome_usuario)
  values (6, 'entregado', '2026-04-18T12:00:00Z', '2026-04-18T12:05:00Z', 'efectivo', 2.91, 0, 0, 3.20, 0.29, null, 'tpv', null)
  returning id into order_six;

  insert into public.order_items (order_id, sort_order, category_sku, category_name, flavors, toppings, unit_price, quantity)
  values (order_six, 1, 'cone', 'Cono', public.serialize_flavors(array['mango_alphonso']), '[]'::jsonb, 3.20, 1);

  update public.orders
  set verifactu_qr = jsonb_build_object(
    'id', concat('pedido-', numero_sequencial),
    'fecha', created_at::date,
    'importe', to_char(total, 'FM999999990.00'),
    'establecimiento', 'Heladeria Sabadell Nord'
  )::text;

  perform setval(pg_get_serial_sequence('public.orders', 'numero_sequencial'), coalesce((select max(numero_sequencial) from public.orders), 1), true);
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- GRANTS
-- ═══════════════════════════════════════════════════════════════════

grant execute on function public.create_demo_order(jsonb, text, jsonb) to anon, authenticated;
grant execute on function public.update_order_status(uuid, text) to anon, authenticated;
grant execute on function public.adjust_flavor_stock(text, numeric) to anon, authenticated;
grant execute on function public.set_flavor_availability(text, boolean) to anon, authenticated;
grant execute on function public.upsert_store_settings(jsonb) to anon, authenticated;
grant execute on function public.reset_demo_data() to anon, authenticated;
grant execute on function public.get_products_by_category(text) to anon, authenticated;
grant execute on function public.update_product_stock(text, boolean) to anon, authenticated;

-- ═══════════════════════════════════════════════════════════════════
-- REALTIME
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  begin alter publication supabase_realtime add table public.categories; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.flavors; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.toppings; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.products; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.store_settings; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.orders; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.order_items; exception when duplicate_object then null; end;
end $$;

select public.reset_demo_data();
